### ISSUE TITLE
Create Snapper

### ISSUE THREAD

**Issue by EliCDavis** [EliCDavis/AssociationEngine#2]
Snapper should be able to subscribe to a Raw Sensor, and publish data to it's subscribers.

- [ ] Determine output format for interfacing with Variable
- [ ] Determine expected input value from Raw Sensor
- [ ] Implement algorithm to convert from input to output
- [ ] Implement actual publish-subscribe connections to Raw Sensor and Variable objects

**Comment by RickArendall** [comment]
Better served by splitting this task into multiple
