### ISSUE TITLE
Make Tox Work on Windows

### ISSUE THREAD

**Issue by EliCDavis** [EliCDavis/AssociationEngine#36]

**Comment by JacobAMason** [comment]
Tox will never work on Windows, at least for those using any version of the Anaconda packaging of Python. Anaconda is somewhat analogous to virtualenv in that they both accomplish similar goals of creating Python environment, Anaconda with the conda command and virtualenv with the wrapper or whatnot. Tox is designed only to work with virtualenv, so it is incompatible with Anaconda.

It is still possible to run tests using pytest, and if you need to test flake8 before you push, you can run it standalone too.
