### ISSUE TITLE
Be Able To Feed Program Spread Sheet Of Data and Run From There

### ISSUE THREAD

**Issue by EliCDavis** [EliCDavis/AssociationEngine#38]
## This Serves Two Purposes
1. This spread sheet should be used for integration testing
2. What will be run as an example for the demo

Realistically, sensors don't follow perfect functions like Sine and Cosine.
Instead, we should have a sensors read a spreadsheet column to get it's values. This is a sufficient way to simulate "real-life" data.

**Comment by JacobAMason** [comment]
This has been started in feature/spreadsheet-integration-test

**Comment by EliCDavis** [comment]
Completed With #68
