### ISSUE TITLE
Relationship Mock Class

### ISSUE THREAD

**Issue by EliCDavis** [EliCDavis/AssociationEngine#41]
Create a `MockRelationship` class that inherits from the `Relationship` class that makes testing the parts of the system easier and more reliable.

**Comment by nathantfrank** [comment]
What are the inconsistent areas dealing with the relationship class that the mock class needs to handle?

**Comment by EliCDavis** [comment]
See [here](https://github.com/EliCDavis/AssociationEngine/pull/40/files/86f5148f87ded30d1918e46bacadca8f2a440ce8#diff-03c2dee4a8716394c0180b3b15f714e3R53).  We need to be able to simulate a relationships emitted association value so the snapper team can make better tests on some of their functionality.

**Comment by nathantfrank** [comment]
Okay, why aren't we using the SpearframeRelationship for testing that? 
(side note appears that the method `SpearframeRelationship.get_correlation_coefficient()` is not implemented) 
Does it add some sort of randomness that I am unaware of or is it just to be easily computable?

**Comment by EliCDavis** [comment]
Well, if we where to change the implementation of spearframe that then changes the values it outputs, tests over the snapper module would break too.  This can be avoided if they can explicitly tell the relationship what to emit.

**Comment by EliCDavis** [comment]
wait no; do [dis](https://docs.python.org/3/library/unittest.mock.html#quick-guide)
