### ISSUE TITLE
Pandas Package Integration

### ISSUE THREAD

**Issue by DarrianBlack** [EliCDavis/AssociationEngine#6]
http://pandas.pydata.org/pandas-docs/stable/10min.html#

**Comment by JacobAMason** [comment]
What is this?

**Comment by EliCDavis** [comment]
@DarrianBlack thought we might benefit to including this some how in our program.  I told him to make an issue about it and label it as discussion.

**Comment by JacobAMason** [comment]
Is this something you still want done? I'm looking for work

**Comment by EliCDavis** [comment]
If you want to look into how we might use this in the spearframe implementation sure, I don't know if their's really an application for it.  This also goes for numpy utilization.

**Comment by JacobAMason** [comment]
We should really only include things as dependencies if they are necessary.

**Comment by EliCDavis** [comment]
A fair statement.  Another thing we might want to look into is tensorflow (or some other library), that would allow us to easily distribute computation across multiple CPUs, something that would be advantageous for large number of sensors.

**Comment by JacobAMason** [comment]
Tensorflow already has a nice docker image that runs with a jupyter (ipython) notebook. I've used it before and it's nice.

**Comment by EliCDavis** [comment]
Discussion for Tensorflow should be moved to a different issue
